format = """
[  ](fg:#ffffff)\
$directory\
$git_branch\
$git_status\
$nodejs\
$rust\
$golang\
$php\
$time\
$character
"""

[directory]
style = "fg:#ffffff"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

[directory.substitutions]
"Documents" = " "
"Downloads" = " "
"Music" = " "
"Pictures" = " "

[git_branch]
symbol = ""
style = "fg:#ffffff"
format = "[ $symbol $branch ]($style)"

[git_status]
style = "fg:#ffffff"
format = "[ $all_status$ahead_behind ]($style)"

[nodejs]
symbol = ""
style = "fg:#ffffff"
format = "[ $symbol $version ]($style)"

[rust]
symbol = ""
style = "fg:#ffffff"
format = "[ $symbol $version ]($style)"

[golang]
symbol = "ﳑ"
style = "fg:#ffffff"
format = "[ $symbol $version ]($style)"

[php]
symbol = ""
style = "fg:#ffffff"
format = "[ $symbol $version ]($style)"

[time]
disabled = true
time_format = "%R"
style = "fg:#ffffff"
format = "[  $time ]($style)"

[character]
success_symbol = "[❯](fg:#ffffff)"
error_symbol = "[❯](fg:#ffffff)"
